In [1]:
import pandas as pd

from superfv import OutputLoader

In [2]:
def build_df(sim, cats, exclude_first=True):

    slc = slice(2, None) if exclude_first else slice(1, None)

    def get_total_attr(sim, cat, attr):
        times = [
            getattr(timer.data[cat], attr)
            for timer in sim.minisnapshots["stepper_timer"][slc]
        ]
        return sum(times)

    take_step = get_total_attr(sim, "take_step", "cum_time")

    data = []
    for cat in cats:
        data.append(
            dict(
                cat=cat,
                tot_time=get_total_attr(sim, cat, "cum_time"),
                per_time=get_total_attr(sim, cat, "cum_time") / take_step * 100,
                n_calls=get_total_attr(sim, cat, "n_calls"),
            )
        )

    return pd.DataFrame(data)

In [3]:
base_path = "/scratch/gpfs/jp7427/out/timing-of-2d-sine-wave/cupy/"

sim0 = OutputLoader(f"{base_path}p7/GL/N_2048")
sim1 = OutputLoader(f"{base_path}ZS7/N_2048")
sim2 = OutputLoader(f"{base_path}MM7/1rev/no_delta/rtol_0/N_2048")

Successfully read simulation output from "/scratch/gpfs/jp7427/out/timing-of-2d-sine-wave/cupy/p7/GL/N_2048"
Successfully read simulation output from "/scratch/gpfs/jp7427/out/timing-of-2d-sine-wave/cupy/ZS7/N_2048"
Successfully read simulation output from "/scratch/gpfs/jp7427/out/timing-of-2d-sine-wave/cupy/MM7/1rev/no_delta/rtol_0/N_2048"

In [4]:
df0 = build_df(
    sim0,
    [
        "update_workspaces",
        "update_workspaces:ucc",
        "update_workspaces:wp",
        "interpolate_faces",
        "interpolate_faces:GL",
        "integrate_fluxes",
        "integrate_fluxes:fallback",
        "integrate_fluxes:riemann_solver",
        "integrate_fluxes:GL",
    ],
)
df1 = build_df(
    sim1,
    [
        "update_workspaces",
        "update_workspaces:ucc",
        "update_workspaces:wp",
        "update_workspaces:shock_detector",
        "interpolate_faces",
        "interpolate_faces:GL",
        "zhang_shu_limiter",
        "integrate_fluxes",
        "integrate_fluxes:fallback",
        "integrate_fluxes:riemann_solver",
        "integrate_fluxes:GL",
        "slope_limiter:detect_smooth_extrema",
    ],
)

df2 = build_df(
    sim2,
    [
        "update_workspaces",
        "update_workspaces:ucc",
        "interpolate_faces",
        "interpolate_faces:transverse",
        "reconstruct_muscl_faces",
        "integrate_fluxes",
        "integrate_fluxes:fallback",
        "integrate_fluxes:riemann_solver",
        "integrate_fluxes:transverse",
        "MOOD_loop",
        "MOOD_loop:compute_fallback_fluxes",
        "MOOD_loop:detect_troubled_cells",
        "MOOD_loop:revise_fluxes",
        "slope_limiter:detect_smooth_extrema",
    ],
)

In [5]:
df0

                               cat  tot_time   per_time  n_calls
0                update_workspaces  0.097793  10.859320       27
1            update_workspaces:ucc  0.033757   3.748469       27
2             update_workspaces:wp  0.034871   3.872181       27
3                interpolate_faces  0.453398  50.346955       54
4             interpolate_faces:GL  0.334936  37.192492       54
5                 integrate_fluxes  0.258348  28.687829       54
6        integrate_fluxes:fallback  0.049274   5.471564       54
7  integrate_fluxes:riemann_solver  0.146672  16.286983       54
8              integrate_fluxes:GL  0.044972   4.993816       54

In [6]:
df1

                                    cat  tot_time   per_time  n_calls
0                     update_workspaces  0.177231   8.412865       27
1                 update_workspaces:ucc  0.033712   1.600235       27
2                  update_workspaces:wp  0.033635   1.596590       27
3      update_workspaces:shock_detector  0.052753   2.504117       27
4                     interpolate_faces  0.457440  21.713899       54
5                  interpolate_faces:GL  0.337285  16.010344       54
6                     zhang_shu_limiter  1.128986  53.591073       27
7                      integrate_fluxes  0.243549  11.560837       54
8             integrate_fluxes:fallback  0.032717   1.553014       54
9       integrate_fluxes:riemann_solver  0.148341   7.041507       54
10                  integrate_fluxes:GL  0.045089   2.140285       54
11  slope_limiter:detect_smooth_extrema  0.095342   4.525728       27

In [7]:
df2

                                    cat  tot_time   per_time  n_calls
0                     update_workspaces  0.062692   2.521949       27
1                 update_workspaces:ucc  0.033623   1.352580       27
2                     interpolate_faces  0.103669   4.170330       54
3          interpolate_faces:transverse  0.071195   2.863980       54
4               reconstruct_muscl_faces  0.326428  13.131388       27
5                      integrate_fluxes  0.167125   6.723012      108
6             integrate_fluxes:fallback  0.000000   0.000000        0
7       integrate_fluxes:riemann_solver  0.079777   3.209210      108
8           integrate_fluxes:transverse  0.052814   2.124585      108
9                             MOOD_loop  2.129788  85.676070       27
10    MOOD_loop:compute_fallback_fluxes  0.473424  19.044680       27
11      MOOD_loop:detect_troubled_cells  1.533857  61.703242       54
12              MOOD_loop:revise_fluxes  0.121809   4.900076       27
13  slope_limiter:detect_smooth_extrema  0.188295   7.574656       54