In [1]:
import pandas as pd

from superfv import OutputLoader

In [2]:
def build_df(sim, cats, exclude_first=True):

    slc = slice(2, None) if exclude_first else slice(1, None)

    def get_total_attr(sim, cat, attr):
        times = [
            getattr(timer.data[cat], attr)
            for timer in sim.minisnapshots["stepper_timer"][slc]
        ]
        return sum(times)

    take_step = get_total_attr(sim, "take_step", "cum_time")

    data = []
    for cat in cats:
        data.append(
            dict(
                cat=cat,
                tot_time=get_total_attr(sim, cat, "cum_time"),
                per_time=get_total_attr(sim, cat, "cum_time") / take_step * 100,
                n_calls=get_total_attr(sim, cat, "n_calls"),
            )
        )

    return pd.DataFrame(data)

In [3]:
base_path = "/scratch/gpfs/jp7427/out/timing-of-2d-sine-wave/cupy/"

sim0 = OutputLoader(f"{base_path}p7/GL/N_2048")
sim1 = OutputLoader(f"{base_path}ZS7/N_2048")
sim2 = OutputLoader(f"{base_path}MM7/1rev/no_delta/rtol_0/N_2048")

Successfully read simulation output from "/scratch/gpfs/jp7427/out/timing-of-2d-sine-wave/cupy/p7/GL/N_2048"
Successfully read simulation output from "/scratch/gpfs/jp7427/out/timing-of-2d-sine-wave/cupy/ZS7/N_2048"
Successfully read simulation output from "/scratch/gpfs/jp7427/out/timing-of-2d-sine-wave/cupy/MM7/1rev/no_delta/rtol_0/N_2048"

In [4]:
df0 = build_df(
    sim0,
    [
        "update_workspaces",
        "update_workspaces:ucc",
        "update_workspaces:wp",
        "interpolate_faces",
        "interpolate_faces:GL",
        "integrate_fluxes",
        "integrate_fluxes:fallback",
        "integrate_fluxes:riemann_solver",
        "integrate_fluxes:GL",
    ],
)
df1 = build_df(
    sim1,
    [
        "update_workspaces",
        "update_workspaces:ucc",
        "update_workspaces:wp",
        "update_workspaces:shock_detector",
        "interpolate_faces",
        "interpolate_faces:GL",
        "zhang_shu_limiter",
        "integrate_fluxes",
        "integrate_fluxes:fallback",
        "integrate_fluxes:riemann_solver",
        "integrate_fluxes:GL",
        "slope_limiter:detect_smooth_extrema",
    ],
)

df2 = build_df(
    sim2,
    [
        "update_workspaces",
        "update_workspaces:ucc",
        "interpolate_faces",
        "interpolate_faces:transverse",
        "reconstruct_muscl_faces",
        "integrate_fluxes",
        "integrate_fluxes:fallback",
        "integrate_fluxes:riemann_solver",
        "integrate_fluxes:transverse",
        "MOOD_loop",
        "MOOD_loop:compute_fallback_fluxes",
        "MOOD_loop:detect_troubles",
        "detect_troubles:NAD",
        "detect_troubles:PAD",
        "MOOD_loop:revise_fluxes",
        "slope_limiter:detect_smooth_extrema",
    ],
)

In [5]:
df0

                               cat  tot_time   per_time  n_calls
0                update_workspaces  0.096860  10.724140       27
1            update_workspaces:ucc  0.033604   3.720577       27
2             update_workspaces:wp  0.033716   3.732943       27
3                interpolate_faces  0.455089  50.386294       54
4             interpolate_faces:GL  0.336156  37.218400       54
5                 integrate_fluxes  0.259161  28.693675       54
6        integrate_fluxes:fallback  0.049791   5.512754       54
7  integrate_fluxes:riemann_solver  0.146672  16.239131       54
8              integrate_fluxes:GL  0.045230   5.007752       54

In [6]:
df1

                                    cat  tot_time   per_time  n_calls
0                     update_workspaces  0.179875   8.629763       27
1                 update_workspaces:ucc  0.034207   1.641147       27
2                  update_workspaces:wp  0.033791   1.621186       27
3      update_workspaces:shock_detector  0.052374   2.512722       27
4                     interpolate_faces  0.458936  22.018072       54
5                  interpolate_faces:GL  0.338359  16.233240       54
6                     zhang_shu_limiter  1.102224  52.880714       27
7                      integrate_fluxes  0.244315  11.721329       54
8             integrate_fluxes:fallback  0.032987   1.582608       54
9       integrate_fluxes:riemann_solver  0.148388   7.119137       54
10                  integrate_fluxes:GL  0.045126   2.164975       54
11  slope_limiter:detect_smooth_extrema  0.095554   4.584334       27

In [7]:
df2

                                    cat  tot_time   per_time  n_calls
0                     update_workspaces  0.062948   2.428730       27
1                 update_workspaces:ucc  0.033568   1.295163       27
2                     interpolate_faces  0.103870   4.007644       54
3          interpolate_faces:transverse  0.071166   2.745799       54
4               reconstruct_muscl_faces  0.326570  12.600124       27
5                      integrate_fluxes  0.166251   6.414478      108
6             integrate_fluxes:fallback  0.000000   0.000000        0
7       integrate_fluxes:riemann_solver  0.079793   3.078666      108
8           integrate_fluxes:transverse  0.053053   2.046973      108
9                             MOOD_loop  2.239876  86.421597       27
10    MOOD_loop:compute_fallback_fluxes  0.470039  18.135616       27
11            MOOD_loop:detect_troubles  1.646986  63.545991       54
12                  detect_troubles:NAD  1.440593  55.582687       54
13                  detect_troubles:PAD  0.017886   0.690111       54
14              MOOD_loop:revise_fluxes  0.122336   4.720123       27
15  slope_limiter:detect_smooth_extrema  0.188654   7.278858       54