In [1]:
import pandas as pd

from superfv import OutputLoader

In [2]:
def build_df(sim, cats, exclude_first=True):

    slc = slice(2, None) if exclude_first else slice(1, None)

    def get_total_attr(sim, cat, attr):
        times = [
            getattr(timer.data[cat], attr)
            for timer in sim.minisnapshots["stepper_timer"][slc]
        ]
        return sum(times)

    take_step = get_total_attr(sim, "take_step", "cum_time")

    data = []
    for cat in cats:
        data.append(
            dict(
                cat=cat,
                tot_time=get_total_attr(sim, cat, "cum_time"),
                per_time=get_total_attr(sim, cat, "cum_time") / take_step * 100,
                n_calls=get_total_attr(sim, cat, "n_calls"),
            )
        )

    return pd.DataFrame(data)

In [3]:
base_path = "/scratch/gpfs/jp7427/out/timing-of-2d-sine-wave/cupy/"

sim0 = OutputLoader(f"{base_path}p7/GL/N_1024")
sim1 = OutputLoader(f"{base_path}ZS7/N_1024")
# sim = OutputLoader(f"{base_path}MM7/3revs/no_delta/rtol_1e-5/N_2048")

Successfully read simulation output from "/scratch/gpfs/jp7427/out/timing-of-2d-sine-wave/cupy/p7/GL/N_1024"
Successfully read simulation output from "/scratch/gpfs/jp7427/out/timing-of-2d-sine-wave/cupy/ZS7/N_1024"

In [16]:
cats = [
    # "compute_dt",
    # "apply_bc",
    "update_workspaces",
    "update_workspaces:ucc",
    "update_workspaces:wp",
    "update_workspaces:shock_detector",
    "interpolate_faces",
    "interpolate_faces:GL",
    # "interpolate_faces:transverse",
    # "reconstruct_muscl_faces",
    "zhang_shu_limiter",
    "integrate_fluxes",
    "integrate_fluxes:fallback",
    "integrate_fluxes:riemann_solver",
    "integrate_fluxes:GL",
    # "integrate_fluxes:transverse",
    # "MOOD_loop",
    # "compute_RHS",
    "slope_limiter:detect_smooth_extrema",
    # "MOOD_loop:compute_fallback_fluxes",
    # "MOOD_loop:detect_troubled_cells",
    # "MOOD_loop:revise_fluxes",
]

df0 = build_df(sim0, cats)
df1 = build_df(sim1, cats)

In [17]:
df0

                                    cat  tot_time   per_time  n_calls
0                     update_workspaces  0.036627  13.001723       27
1                 update_workspaces:ucc  0.011278   4.003383       27
2                  update_workspaces:wp  0.011205   3.977337       27
3      update_workspaces:shock_detector  0.000000   0.000000        0
4                     interpolate_faces  0.139743  49.604919       54
5                  interpolate_faces:GL  0.104953  37.255454       54
6                     zhang_shu_limiter  0.000000   0.000000        0
7                      integrate_fluxes  0.078176  27.750262       54
8             integrate_fluxes:fallback  0.017847   6.335268       54
9       integrate_fluxes:riemann_solver  0.039529  14.031751       54
10                  integrate_fluxes:GL  0.013514   4.797062       54
11  slope_limiter:detect_smooth_extrema  0.000000   0.000000        0

In [18]:
df1

                                    cat  tot_time   per_time  n_calls
0                     update_workspaces  0.057620   9.719692       27
1                 update_workspaces:ucc  0.009979   1.683253       27
2                  update_workspaces:wp  0.009910   1.671691       27
3      update_workspaces:shock_detector  0.014492   2.444581       27
4                     interpolate_faces  0.125996  21.254020       54
5                  interpolate_faces:GL  0.091475  15.430604       54
6                     zhang_shu_limiter  0.308603  52.057453       27
7                      integrate_fluxes  0.070944  11.967302       54
8             integrate_fluxes:fallback  0.010684   1.802280       54
9       integrate_fluxes:riemann_solver  0.040063   6.758201       54
10                  integrate_fluxes:GL  0.013047   2.200933       54
11  slope_limiter:detect_smooth_extrema  0.042083   7.098927       27