In [1]:
import pandas as pd

from superfv import OutputLoader

In [2]:
def build_df(sim, cats, exclude_first=True):

    slc = slice(2, None) if exclude_first else slice(1, None)

    def get_total_attr(sim, cat, attr):
        times = [
            getattr(timer.data[cat], attr)
            for timer in sim.minisnapshots["stepper_timer"][slc]
        ]
        return sum(times)

    take_step = get_total_attr(sim, "take_step", "cum_time")

    data = []
    for cat in cats:
        data.append(
            dict(
                cat=cat,
                tot_time=get_total_attr(sim, cat, "cum_time"),
                per_time=get_total_attr(sim, cat, "cum_time") / take_step * 100,
                n_calls=get_total_attr(sim, cat, "n_calls"),
            )
        )

    return pd.DataFrame(data)

In [3]:
base_path = "/scratch/gpfs/jp7427/out/timing-of-2d-sine-wave/cupy/"

sim0 = OutputLoader(f"{base_path}p7/GL/N_2048")
sim1 = OutputLoader(f"{base_path}ZS7/N_2048")
sim2 = OutputLoader(f"{base_path}MM7/1rev/no_delta/rtol_1e-5/N_2048")

Successfully read simulation output from "/scratch/gpfs/jp7427/out/timing-of-2d-sine-wave/cupy/p7/GL/N_2048"
Successfully read simulation output from "/scratch/gpfs/jp7427/out/timing-of-2d-sine-wave/cupy/ZS7/N_2048"
Successfully read simulation output from "/scratch/gpfs/jp7427/out/timing-of-2d-sine-wave/cupy/MM7/1rev/no_delta/rtol_1e-5/N_2048"

In [4]:
df0 = build_df(
    sim0,
    [
        "update_workspaces",
        "update_workspaces:ucc",
        "update_workspaces:wp",
        "interpolate_faces",
        "interpolate_faces:GL",
        "integrate_fluxes",
        "integrate_fluxes:fallback",
        "integrate_fluxes:riemann_solver",
        "integrate_fluxes:GL",
    ],
)
df1 = build_df(
    sim1,
    [
        "update_workspaces",
        "update_workspaces:ucc",
        "update_workspaces:wp",
        "update_workspaces:shock_detector",
        "interpolate_faces",
        "interpolate_faces:GL",
        "zhang_shu_limiter",
        "integrate_fluxes",
        "integrate_fluxes:fallback",
        "integrate_fluxes:riemann_solver",
        "integrate_fluxes:GL",
        "slope_limiter:detect_smooth_extrema",
    ],
)

df2 = build_df(
    sim2,
    [
        "update_workspaces",
        "update_workspaces:ucc",
        "interpolate_faces",
        "interpolate_faces:transverse",
        "reconstruct_muscl_faces",
        "integrate_fluxes",
        "integrate_fluxes:fallback",
        "integrate_fluxes:riemann_solver",
        "integrate_fluxes:transverse",
        "MOOD_loop",
        "MOOD_loop:compute_fallback_fluxes",
        "MOOD_loop:detect_troubled_cells",
        "MOOD_loop:revise_fluxes",
        "slope_limiter:detect_smooth_extrema",
    ],
)

In [5]:
df0

                               cat  tot_time   per_time  n_calls
0                update_workspaces  0.096451  10.719987       27
1            update_workspaces:ucc  0.033591   3.733507       27
2             update_workspaces:wp  0.033578   3.731993       27
3                interpolate_faces  0.454035  50.463597       54
4             interpolate_faces:GL  0.335194  37.254986       54
5                 integrate_fluxes  0.258346  28.713755       54
6        integrate_fluxes:fallback  0.049467   5.497950       54
7  integrate_fluxes:riemann_solver  0.146699  16.304771       54
8              integrate_fluxes:GL  0.044947   4.995651       54

In [6]:
df1

                                    cat  tot_time   per_time  n_calls
0                     update_workspaces  0.177550   8.406448       27
1                 update_workspaces:ucc  0.033799   1.600266       27
2                  update_workspaces:wp  0.033764   1.598607       27
3      update_workspaces:shock_detector  0.052437   2.482742       27
4                     interpolate_faces  0.458473  21.707319       54
5                  interpolate_faces:GL  0.337975  16.002121       54
6                     zhang_shu_limiter  1.130643  53.532595       27
7                      integrate_fluxes  0.243427  11.525557       54
8             integrate_fluxes:fallback  0.032812   1.553568       54
9       integrate_fluxes:riemann_solver  0.148444   7.028406       54
10                  integrate_fluxes:GL  0.045041   2.132550       54
11  slope_limiter:detect_smooth_extrema  0.095382   4.516067       27

In [7]:
df2

                                    cat  tot_time   per_time  n_calls
0                     update_workspaces  0.062899   1.956938       27
1                 update_workspaces:ucc  0.033641   1.046656       27
2                     interpolate_faces  0.103895   3.232403       54
3          interpolate_faces:transverse  0.071154   2.213765       54
4               reconstruct_muscl_faces  0.892390  27.764363       27
5                      integrate_fluxes  0.166134   5.168833      108
6             integrate_fluxes:fallback  0.000000   0.000000        0
7       integrate_fluxes:riemann_solver  0.079698   2.479604      108
8           integrate_fluxes:transverse  0.053064   1.650950      108
9                             MOOD_loop  2.858324  88.929188       27
10    MOOD_loop:compute_fallback_fluxes  1.035912  32.229667       27
11      MOOD_loop:detect_troubled_cells  1.700123  52.894831       54
12              MOOD_loop:revise_fluxes  0.121784   3.788977       27
13  slope_limiter:detect_smooth_extrema  0.362579  11.280677       54