In [1]:
import pandas as pd

from superfv import OutputLoader

In [2]:
def build_df(sim, cats, exclude_first=True):

    slc = slice(2, None) if exclude_first else slice(1, None)

    def get_total_attr(sim, cat, attr):
        times = [
            getattr(timer.data[cat], attr) for timer in sim.minisnapshots["stepper_timer"][slc]
        ]
        return sum(times)

    take_step = get_total_attr(sim, "take_step", "cum_time")

    data = []
    for cat in cats:
        data.append(
            dict(
                cat=cat,
                tot_time=get_total_attr(sim, cat, "cum_time"),
                per_time=get_total_attr(sim, cat, "cum_time") / take_step * 100,
                n_calls=get_total_attr(sim, cat, "n_calls"),
            )
        )

    return pd.DataFrame(data)

In [4]:
base_path = "/scratch/gpfs/jp7427/out/timing-of-2d-sine-wave/cupy/"

sim0 = OutputLoader(f"{base_path}p7/GL/N_2048")
sim1 = OutputLoader(f"{base_path}ZS7/N_2048")
sim2 = OutputLoader(f"{base_path}MM7/1rev/rtol_0/N_2048")

Successfully read simulation output from "/scratch/gpfs/jp7427/out/timing-of-2d-sine-wave/cupy/p7/GL/N_2048"
Successfully read simulation output from "/scratch/gpfs/jp7427/out/timing-of-2d-sine-wave/cupy/ZS7/N_2048"
Successfully read simulation output from "/scratch/gpfs/jp7427/out/timing-of-2d-sine-wave/cupy/MM7/1rev/rtol_0/N_2048"

In [11]:
df0 = build_df(
    sim0,
    [
        "take_step",
        "update_workspaces",
        "update_workspaces:ucc",
        "update_workspaces:wp",
        "interpolate_faces",
        "interpolate_faces:GL",
        "integrate_fluxes",
        "integrate_fluxes:fallback",
        "integrate_fluxes:riemann_solver",
        "integrate_fluxes:GL",
    ],
)
df1 = build_df(
    sim1,
    [
        "take_step",
        "update_workspaces",
        "update_workspaces:ucc",
        "update_workspaces:wp",
        "update_workspaces:shock_detector",
        "interpolate_faces",
        "interpolate_faces:GL",
        "zhang_shu_limiter",
        "integrate_fluxes",
        "integrate_fluxes:fallback",
        "integrate_fluxes:riemann_solver",
        "integrate_fluxes:GL",
        "slope_limiter:detect_smooth_extrema",
    ],
)

df2 = build_df(
    sim2,
    [
        "take_step",
        "update_workspaces",
        "update_workspaces:ucc",
        "interpolate_faces",
        "interpolate_faces:transverse",
        "reconstruct_muscl_faces",
        "integrate_fluxes",
        "integrate_fluxes:fallback",
        "integrate_fluxes:riemann_solver",
        "integrate_fluxes:transverse",
        "MOOD_loop",
        "MOOD_loop:compute_fallback_fluxes",
        "MOOD_loop:detect_troubles",
        "detect_troubles:NAD",
        "detect_troubles:PAD",
        "MOOD_loop:revise_fluxes",
        "slope_limiter:detect_smooth_extrema",
    ],
)

In [12]:
df0

                               cat  tot_time    per_time  n_calls
0                        take_step  0.794274  100.000000        9
1                update_workspaces  0.106990   13.470182       27
2            update_workspaces:ucc  0.038905    4.898126       27
3             update_workspaces:wp  0.038658    4.867036       27
4                interpolate_faces  0.364801   45.928842       54
5             interpolate_faces:GL  0.245140   30.863415       54
6                 integrate_fluxes  0.231748   29.177378       54
7        integrate_fluxes:fallback  0.032629    4.108036       54
8  integrate_fluxes:riemann_solver  0.146951   18.501230       54
9              integrate_fluxes:GL  0.035234    4.435970       54

In [13]:
df1

                                    cat  tot_time    per_time  n_calls
0                             take_step  2.000067  100.000000        9
1                     update_workspaces  0.173931    8.696277       27
2                 update_workspaces:ucc  0.038692    1.934559       27
3                  update_workspaces:wp  0.038368    1.918351       27
4      update_workspaces:shock_detector  0.037744    1.887147       27
5                     interpolate_faces  0.366808   18.339760       54
6                  interpolate_faces:GL  0.246201   12.309648       54
7                     zhang_shu_limiter  1.126696   56.332895       27
8                      integrate_fluxes  0.233670   11.683090       54
9             integrate_fluxes:fallback  0.032861    1.643008       54
10      integrate_fluxes:riemann_solver  0.148445    7.422020       54
11                  integrate_fluxes:GL  0.035465    1.773200       54
12  slope_limiter:detect_smooth_extrema  0.095801    4.789877       27

In [14]:
df2

                                    cat  tot_time    per_time  n_calls
0                             take_step  1.296384  100.000000        9
1                     update_workspaces  0.067552    5.210829       27
2                 update_workspaces:ucc  0.038262    2.951460       27
3                     interpolate_faces  0.127419    9.828787       54
4          interpolate_faces:transverse  0.094429    7.284065       54
5               reconstruct_muscl_faces  0.165289   12.749989       27
6                      integrate_fluxes  0.179657   13.858308      108
7             integrate_fluxes:fallback  0.000000    0.000000        0
8       integrate_fluxes:riemann_solver  0.079844    6.158944      108
9           integrate_fluxes:transverse  0.066129    5.101052      108
10                            MOOD_loop  0.911570   70.316375       27
11    MOOD_loop:compute_fallback_fluxes  0.290451   22.404723       27
12            MOOD_loop:detect_troubles  0.497790   38.398312       54
13                  detect_troubles:NAD  0.000000    0.000000        0
14                  detect_troubles:PAD  0.000000    0.000000        0
15              MOOD_loop:revise_fluxes  0.122864    9.477432       27
16  slope_limiter:detect_smooth_extrema  0.188418   14.534094       54